targets:
  $default:
    builders:
      app_finance|gherkin_generic_generator:
        enabled: true
      app_finance|class_list_generator:
        enabled: true

builders:
  gherkin_generic_generator:
    import: "package:app_finance/_classes/gen/gherkin_generic_generator.dart"
    builder_factories: ["gherkinGenericGenerator"]
    build_extensions: {".dart": [".generic.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  class_list_generator:
    import: "package:app_finance/_classes/gen/class_list_generator.dart"
    builder_factories: ["classListGenerator"]
    build_extensions: {".dart": [".list.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]