name: Fingrom
base: core22
version: 1.0.0+1
summary: Open-source platform-agnostic financial accounting application
description: |
  The goal of the solution is to create a financial accounting application that is intuitive, efficient, 
  and inclusive. That empowers users to effortlessly manage their finances while ensuring that no one is left behind.

grade: stable
confinement: strict

parts:
  app-finance:
    source: .
    plugin: flutter
    build-packages: [libgtk-3-dev, ninja-build]
    flutter-target: lib/main.dart