name: fingrom
base: core22
version: 1.0.0+1
summary: Open-source platform-agnostic financial accounting application
description: |
  The goal of the solution is to create a financial accounting application that is intuitive, efficient, 
  and inclusive. That empowers users to effortlessly manage their finances while ensuring that no one is left behind.

grade: stable
confinement: strict

apps:
  fingrom:
    command: fingrom
    plugs: [home, desktop, desktop-legacy, network, network-bind, opengl, x11]
    extensions: [gnome]

parts:
  app-finance:
    source: .
    plugin: flutter
    build-packages: [libgtk-3-dev, ninja-build]
    stage-packages: [libgtk-3-0]
    flutter-target: lib/main.dart