name: Bind Reports to Pull-Request

on:
  workflow_run:
    workflows: [Generate Reports]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get Artifacts Link
        env:
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
          GH_TOKEN: ${{ github.token }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          ARTIFACT_URL=$(gh api "/repos/${{ github.repository }}/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            .archive_download_url")
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        env:
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
          PR_NOTES: |
            Build artifacts:
            | Name | Link |
            |------|------|
            | Dependencies Graph | [dependencies.svg](${ARTIFACT_URL}) |
        with:
          script: |
            PR_NUMBER=$(jq -r '.pull_requests[0].number' <<< "$WORKFLOW_RUN_EVENT_OBJ")
            github.rest.issues.createComment({
              issue_number: PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "$PR_NOTES"
            })

