# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter/Dart Quality Gates

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Check Localizations ordering
        run: dart run grinder sort-translations

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      #- name: Analyze Project Source
      #  run: flutter analyze

      - name: Run tests
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            dart run grinder test --coverage --path=test/unit
            dart run grinder test --path=test/widget
            dart run grinder test --path=test/e2e
          else
            dart run grinder test
          fi

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage